language:
    - go
    - python
go:
    - tip

python:
    - "2.7"
    
sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq redis-server postgresql sqlite3
  - pip install requests nose


install:
    - export GOPATH=$GOPATH:$HOME/gopath/src/github.com/dkumor/connectordb
    - make dependencies

script:
    - make coverage
    - make
    - make test

notifications:
    slack: connectordb:3YIEG5E8KpOqaNbScZv0Rs0r
