language: go
go:
    - tip

install:
    - export GOPATH=$GOPATH:$HOME/gopath/src/github.com/dkumor/connectordb
    - make dependencies

script:
    - make coverage
    - make
    - make test

notifications:
    email:
        recipients:
            - daniel@dkumor.com
            - joseph@josephlewis.net
