os:
    - linux
    - osx

language:
    - go

go:
    - 1.8

# travis clones 50 deep - we only need 1
git:
    depth: 1

virtualenv:
    system_site_packages: true

# All this because of https://github.com/travis-ci/travis-ci/issues/3130
env:
    - TRAVIS_NODE_VERSION="4"

before_install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then brew update; brew install redis;fi   # Darwin does not have redis by default
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION #http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
    - npm install -g yarn

# Here is the actual ConnectorDB script
install:
    - export GOPATH=$GOPATH:$HOME/gopath/src/github.com/connectordb/connectordb
    - export PATH=$HOME/.local/bin:$PATH
    - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then export PATH=$HOME/Library/Python/2.7/bin/:$PATH;fi   # OSX uses different directory for local install of python libs
    - pip install --user nose requests jsonschema websocket-client coverage
    - make deps

script:
    - make testbuild
    - make test
