# This file is based on https://github.com/mholt/caddy/blob/master/appveyor.yml
# Didn't realize that windows builds were possible before looking at caddy.
#
# In Windows, we have to be careful with the build process, since we need to
# have all of the servers enabled and in path. TODO: right now it just builds connectordb executable

version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\connectordb

environment:
  GOPATH: c:\connectordb


install:
  - set PATH=C:\msys64\mingw64\bin;%PATH%;%GOPATH%\bin
  - set CC=gcc
  - git submodule update --init --recursive
  # Set up golang - based on https://github.com/joefitzgerald/go-plus/blob/master/appveyor.yml
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.7.windows-amd64.zip
  - 7z x go1.7.windows-amd64.zip -y -oC:\ > NUL
   # Set up redis,node, gnatsd
  - nuget install redis-64 -excludeversion
  - ps: Install-Product node 0
  - appveyor DownloadFile https://github.com/nats-io/gnatsd/releases/download/v0.9.4/gnatsd-v0.9.4-windows-amd64.zip
  - 7z x gnatsd-v0.9.4-windows-amd64.zip -y -oC:\connectordb\ > NUL
  - if not exist "C:\connectordb\bin" mkdir C:\connectordb\bin
  - move C:\connectordb\gnatsd-v0.9.4-windows-amd64 C:\connectordb\bin\dep
  # Print dependencies and versions
  - go version
  - go env
  - where gcc
  - where mingw32-make
 
  # Build the ConnectorDB executable
  - dependencies.bat
  - build.bat

build: off

test_script:
  - bin\connectordb.exe --version
  - bin\connectordb.exe -l=DEBUG create testdb --sqlbackend=sqlite3

deploy: off
